<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>sushi</string>
    </array>
    <key>name</key>
    <string>Sushi</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>#comments</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#keywords</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#types</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#constants</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#strings</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#numbers</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#operators</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#function-declaration</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#function-call</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#method-call</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#struct-declaration</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#enum-declaration</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#struct-constructor</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#enum-variant</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#user-types</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#array-types</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#io-streams</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#punctuation</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>comments</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>#.*$</string>
                    <key>name</key>
                    <string>comment.line.number-sign.sushi</string>
                </dict>
            </array>
        </dict>
        <key>keywords</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b(if|elif|else|while|break|continue|return)\b</string>
                    <key>name</key>
                    <string>keyword.control.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(foreach|in|match)\b</string>
                    <key>name</key>
                    <string>keyword.control.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(fn|extend|let|const|struct|enum|use|public)\b</string>
                    <key>name</key>
                    <string>keyword.other.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(as)\b</string>
                    <key>name</key>
                    <string>keyword.operator.word.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(and|or|not)\b</string>
                    <key>name</key>
                    <string>keyword.operator.logical.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(print|println)\b</string>
                    <key>name</key>
                    <string>support.function.builtin.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(new|from)\b</string>
                    <key>name</key>
                    <string>support.function.builtin.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(Ok|Err)\b</string>
                    <key>name</key>
                    <string>support.function.result.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(Result)\b</string>
                    <key>name</key>
                    <string>support.class.result.sushi</string>
                </dict>
            </array>
        </dict>
        <key>types</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b(i8|i16|i32|i64|u8|u16|u32|u64|f32|f64)\b</string>
                    <key>name</key>
                    <string>storage.type.numeric.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(bool|string)\b</string>
                    <key>name</key>
                    <string>storage.type.builtin.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(~)\b</string>
                    <key>name</key>
                    <string>storage.type.blank.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(Iterator)\b</string>
                    <key>name</key>
                    <string>support.class.iterator.sushi</string>
                </dict>
            </array>
        </dict>
        <key>array-types</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b([a-zA-Z_][a-zA-Z0-9_]*)\s*(\[\s*\d*\s*\])</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>storage.type.sushi</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>meta.bracket.square.sushi</string>
                        </dict>
                    </dict>
                </dict>
            </array>
        </dict>
        <key>user-types</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b[A-Z][a-zA-Z0-9_]*\b</string>
                    <key>name</key>
                    <string>support.class.sushi</string>
                </dict>
            </array>
        </dict>
        <key>constants</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b(true|false)\b</string>
                    <key>name</key>
                    <string>constant.language.boolean.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(_)\b</string>
                    <key>name</key>
                    <string>constant.language.wildcard.sushi</string>
                </dict>
            </array>
        </dict>
        <key>io-streams</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b(stdin|stdout|stderr)\b</string>
                    <key>name</key>
                    <string>support.variable.magic.sushi</string>
                </dict>
            </array>
        </dict>
        <key>strings</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>"</string>
                    <key>end</key>
                    <string>"</string>
                    <key>name</key>
                    <string>string.quoted.double.sushi</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>match</key>
                            <string>\\(["\\\/bfnrt]|u[0-9a-fA-F]{4})</string>
                            <key>name</key>
                            <string>constant.character.escape.sushi</string>
                        </dict>
                        <dict>
                            <key>begin</key>
                            <string>\{</string>
                            <key>end</key>
                            <string>\}</string>
                            <key>name</key>
                            <string>meta.embedded.line.sushi</string>
                            <key>beginCaptures</key>
                            <dict>
                                <key>0</key>
                                <dict>
                                    <key>name</key>
                                    <string>punctuation.section.embedded.begin.sushi</string>
                                </dict>
                            </dict>
                            <key>endCaptures</key>
                            <dict>
                                <key>0</key>
                                <dict>
                                    <key>name</key>
                                    <string>punctuation.section.embedded.end.sushi</string>
                                </dict>
                            </dict>
                            <key>patterns</key>
                            <array>
                                <dict>
                                    <key>include</key>
                                    <string>$self</string>
                                </dict>
                            </array>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
        <key>numbers</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b\d+\.\d+([eE][+-]?\d+)?\b</string>
                    <key>name</key>
                    <string>constant.numeric.float.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b\d+\b</string>
                    <key>name</key>
                    <string>constant.numeric.integer.sushi</string>
                </dict>
            </array>
        </dict>
        <key>operators</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>(:=|=)</string>
                    <key>name</key>
                    <string>keyword.operator.assignment.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(==|!=|&lt;=|&gt;=|&lt;|&gt;)</string>
                    <key>name</key>
                    <string>keyword.operator.comparison.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(&lt;&lt;|&gt;&gt;|&amp;|\||\^)</string>
                    <key>name</key>
                    <string>keyword.operator.bitwise.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(\+|-|\*|/|%)</string>
                    <key>name</key>
                    <string>keyword.operator.arithmetic.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>-&gt;</string>
                    <key>name</key>
                    <string>keyword.operator.arrow.sushi</string>
                </dict>
            </array>
        </dict>
        <key>punctuation</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\.</string>
                    <key>name</key>
                    <string>punctuation.accessor.dot.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>,</string>
                    <key>name</key>
                    <string>punctuation.separator.comma.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>:</string>
                    <key>name</key>
                    <string>punctuation.separator.colon.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>[\(\)]</string>
                    <key>name</key>
                    <string>meta.brace.round.sushi</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>[\[\]]</string>
                    <key>name</key>
                    <string>meta.brace.square.sushi</string>
                </dict>
            </array>
        </dict>
        <key>function-declaration</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b(fn|extend)\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.other.sushi</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.function.sushi</string>
                        </dict>
                    </dict>
                </dict>
            </array>
        </dict>
        <key>function-call</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b([a-z_][a-zA-Z0-9_]*)\s*\(</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>variable.function.sushi</string>
                        </dict>
                    </dict>
                </dict>
            </array>
        </dict>
        <key>method-call</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\.\s*([a-z_][a-zA-Z0-9_]*)\s*\(</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>variable.function.sushi</string>
                        </dict>
                    </dict>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\.\s*([a-z_][a-zA-Z0-9_]*)\b</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>variable.other.member.sushi</string>
                        </dict>
                    </dict>
                </dict>
            </array>
        </dict>
        <key>struct-declaration</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b(struct)\s+([A-Z][a-zA-Z0-9_]*)\s*:</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.other.sushi</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.type.struct.sushi</string>
                        </dict>
                    </dict>
                </dict>
            </array>
        </dict>
        <key>enum-declaration</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b(enum)\s+([A-Z][a-zA-Z0-9_]*)\s*:</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.other.sushi</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.type.enum.sushi</string>
                        </dict>
                    </dict>
                </dict>
            </array>
        </dict>
        <key>struct-constructor</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b([A-Z][a-zA-Z0-9_]*)\s*\(</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>support.class.sushi</string>
                        </dict>
                    </dict>
                </dict>
            </array>
        </dict>
        <key>enum-variant</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\b([A-Z][a-zA-Z0-9_]*)\.([A-Z][a-zA-Z0-9_]*)\b</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>support.class.sushi</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>constant.other.enum.sushi</string>
                        </dict>
                    </dict>
                </dict>
            </array>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>source.sushi</string>
    <key>uuid</key>
    <string>8E6A7B9C-2D3E-4F5A-9B8C-7D6E5F4A3B2C</string>
</dict>
</plist>
